module.exports = {
    content: [
    { folder: 'angular', files: ['angular.min.js'] },
    { folder: 'angular-animate', files: ['angular-animate.min.js'] },
    { folder: 'angular-bootstrap', files: ['ui-bootstrap.min.js', 'ui-bootstrap-tpls.min.js'] },
    { folder: 'angular-drag-and-drop-lists', files: ['angular-drag-and-drop-lists.min.js'] },
    { folder: 'angular-mocks', files: ['angular-mocks.js'] },
    { folder: 'angular-moment', files: ['angular-moment.min.js'] },
    { folder: 'angular-resource', files: ['angular-resource.min.js'] },
    { folder: 'angular-sanitize', files: ['angular-sanitize.min.js'] },
    { folder: 'angular-smart-table/dist', files: ['smart-table.min.js'], dist: 'angular-smart-table' },
    { folder: 'angular-ui-bootstrap-datetimepicker', files: ['datetimepicker.css', 'datetimepicker.js'] },
    { folder: 'angular-ui-router/release', files: ['angular-ui-router.min.js'], dist: 'angular-ui-router' },
    { folder: 'angular-ui-tinymce/src', files: ['tinymce.js'], dist: 'angular-ui-tinymce' },
    { folder: 'bootstrap/dist/js', files: ['bootstrap.min.js'], dist: 'bootstrap' },
    { folder: 'datetimepicker', files: ['jquery.datetimepicker.js', 'jquery.datetimepicker.css'] },
    { folder: 'flexslider', files: ['jquery.flexslider-min.js', 'flexslider.css'] },
    { folder: 'font-awesome', files: ['css/font-awesome.min.css', 'fonts/*'] },
    { folder: 'fullcalendar/dist', files: ['fullcalendar.min.js', 'fullcalendar.min.css'], dist: 'fullcalendar' },
    { folder: 'jquery/dist', files: ['jquery.min.js'], dist: 'jquery' },
    { folder: 'jquery-ui', files: ['jquery-ui.min.js'] },
    { folder: 'jquery-ui/themes/smoothness/images', files: ['*'], dist: 'jquery-ui/images' },
    { folder: 'jquery-ui/themes/smoothness', files: ['jquery-ui.min.css'], dist: 'jquery-ui' },
    { folder: 'jquery-validation/dist', files: ['jquery.validate.min.js'], dist: 'jquery-validation' },
    { folder: 'magnific-popup/dist', files: ['jquery.magnific-popup.min.js', 'magnific-popup.css'], dist: 'magnific-popup' },
    { folder: 'mixitup', files: ['jquery.mixitup.min.js'] },
    { folder: 'modernizr', files: ['modernizr.js'] },
    { folder: 'moment/min', files: ['moment.min.js'], dist: 'moment' },
    { folder: 'ng-file-upload', files: ['ng-file-upload.min.js', 'ng-file-upload-shim.min.js'] },
    { folder: 'ngstorage', files: ['ngStorage.min.js'] },
    { folder: 'ngtoast/dist', files: ['ngToast-animations.min.css', 'ngToast.min.css', 'ngToast.min.js'], dist: 'ngtoast' },
    { folder: 'ng-csv/build', files: ['ng-csv.min.js'], dist: 'ng-csv' },
    { folder: 'oclazyload/dist', files: ['ocLazyLoad.require.min.js'], dist: 'oclazyload' },
    { folder: 'qtip2', files: ['jquery.qtip.min.js', 'jquery.qtip.min.css'] },
    { folder: 'requirejs', files: ['require.js'] },
    { folder: 'requirejs-plugins/src', files: ['json.js'], dist: 'requirejs-plugins' },
    { folder: 'respond/dest', files: ['respond.min.js'], dist: 'respond' },
    { folder: 'signalr', files: ['jquery.signalR.min.js'] },
    { folder: 'skrollr/dist', files: ['skrollr.min.js'], dist: 'skrollr' },
    { folder: 'text', files: ['text.js'] },
    { folder: 'tg-angular-validator/dist', files: ['angular-validator.min.js'], dist: 'tg-angular-validator'},
    { folder: 'tinymce', files: ['tinymce.min.js', 'plugins/**', 'skins/**', 'themes/**'] },
    { folder: 'underscore', files: ['underscore-min.js'] }
    ],
    fonts: [
        { folder: 'font-awesome/fonts', files: ['*'], dist: '' }
    ]
};

